### ISSUE TITLE
Disable by atmospheric percentage not working

### ISSUE THREAD

**Issue by reseune** [linuxgurugamer/BobsPanicBox#2]
I think I may have found another minor bug. Same install. I have the option to use the % of atmosphere selected and to disable at 66%. However, at 66,000m I received a notification that BPB was disabled due to passing the atmosphere limit. Screenshot and logs here: https://1drv.ms/u/s!AoyHZiRU1jT-zbdvjwKp-E8lUOXpGQ?e=OVFnec, although I didn't catch the message. I can repeat it as necessary.

**Comment by linuxgurugamer** [comment]
Fixed in 0.0.1.21
